name: Create Meeting Issue
env:
  GITHUB_TOKEN: ${{ github.token }}

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * WED'

jobs:
  meeting-issue:
    name: Create FCOS Meeting Issue
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Local Action
        id: meeting-issue
        uses: ./
        with:
          issueTitle: 'FCOS Meeting Checklist'
          rootURLMeetingLogs: 'https://meetbot-raw.fedoraproject.org/teams/fedora_coreos_meeting/'
          trackingRepo: 'coreos/fedora-coreos-tracker'
